---
title: "Nested Data"
format: 
  html:
    page-layout: custom
server: shiny
editor: visual
fig-format: svg
---

Be sure to run `renv::restore()`, and then click on the "Run Document" button.

```{r}
#| panel: sidebar
sliderInput(
  "mu", 
  "μ", 
  min = 400, 
  max = 700, 
  value = 550
)

sliderInput(
  "spcom",
  "Community σ",
  min = 50,
  max = 200,
  value = 125
)

sliderInput(
  "spsigma",
  "Speaker σ",
  min = 50,
  max = 200,
  value = 125
)

sliderInput(
  "nspeak",
  "Number of speakers",
  min = 3,
  max = 10,
  value = 5
)

sliderInput(
  "ndata",
  "Typical n per speaker",
  min = 10,
  max = 50,
  value = 30
)

```

```{r}
#| panel: fill
#| layout: "[[50,50],[50,50]]"
plotOutput(
  "distPlot",
  width = "100%",
  height = "400px"
)

plotOutput(
  "spDists", 
  width = "100%",
  height = "400px"
)

tableOutput(
  "spSummary"
)

plotOutput(
  "spDat",
  width = "100%",
  height = "400px"
  )

```

```{r}
#| context: server
library(tidyverse)
library(distributional)
library(ggdist)
library(tinytable)
theme_set(theme_minimal(base_size = 20))

theme_no_y <- function(){
  theme_sub_axis_y(
    text = element_blank(),
    title = element_blank()
  )
}

dist <- reactive({
  dist_normal(0,input$spcom)
})

dist_samp <- reactive({
  tibble(
    gamma = generate(dist_normal(0, 1), input$nspeak)
  ) |> 
    unnest(gamma) |> 
    mutate(
      speaker = factor(row_number())
    ) 
})
  
gammas <- reactive({  
  dist_samp() |> 
    mutate(
      gamma = gamma * input$spcom
    )
})

output$distPlot <- renderPlot({
  ggplot() + 
    stat_slab(
      aes(xdist = dist()),
      fill = NA,
      color = "black"
    ) + 
    xlim(-400, 400) +
    geom_dots(
      data = gammas(),
      aes(
        x = gamma,
        color = speaker,
        group = 1
      ),
      binwidth = 20,
      shape = "triangle"
    ) +
    labs(
      title = "Speaker offsets",
      x = expression(gamma)
    ) +
    theme_no_y()
})

spDists <- reactive({
  gammas() |> 
    mutate(
      dist = dist_normal(input$mu + gamma, input$spsigma)
    )
})

spGamma <- reactive({
  gammas() |> 
    mutate(
      distg = dist_normal(gamma, 180)
    )
})

spBase <- reactive({
  tibble(
    speaker = as.factor(1:input$nspeak),
    mu1 = 0
  ) |> 
    mutate(
      sdist = dist_normal(mu1, 1),
      f1 = generate(sdist, 100)
    ) |> 
    #unnest(f1) |> 
    select(-sdist)
})

spFilter <- reactive({
  spBase() |> 
    mutate(
      n = rpois(input$nspeak, input$ndata)
    ) |> 
    unnest(f1)
})

spData <- reactive({
  gammas() |> 
    left_join(
      spFilter(),
      by = "speaker"
    ) |> 
    filter(
      .by = speaker,
      row_number() <= n
    ) |>     
    mutate(
      f1 = (f1 * input$spsigma) + input$mu + gamma
    )
})

output$spSummary <- renderTable({
  spData() |> 
    summarise(
      `n` = n(),
      `sample mean` = mean(f1),
      `sample sd` = sd(f1),
      `sample se` = `sample sd` / sqrt(n)
    ) |> 
    mutate(
      across(
        everything(),
        ~round(.x) |> as.integer()
      )
    )
  
  }, 
  width = "50%"
)

output$spDists <- renderPlot({
  spDists() |> 
    ggplot() +
      geom_vline(
        xintercept = input$mu,
        linewidth = 0.5
      ) +
      stat_slab(
        aes(
          xdist = dist,
          color = speaker
        ),
        fill = NA
      ) +
    xlim(0, 1200) +
    labs(x = "f1", title = "Speaker Distributions") +
    theme_no_y()
})

output$spDat <- renderPlot({
  spData() |>
    mutate(
      f1 = case_when(
        f1 < 0 ~ 0,
        f1 > 1200 ~ 1200,
        .default = f1
      )
    ) |>
    ggplot() +
    geom_dots(
      aes(
        x = f1,
        color = speaker,
        group = 1,
        order = speaker
      ),
      shape = "circle",
      binwidth = 15
    ) +
    xlim(0, 1200) +
    labs(
      title = "Observed Data"
    ) +
    theme_no_y()
})

```
